# Kunci unik untuk proyek ini di SonarQube. Tidak boleh ada spasi.
sonar.projectKey=Zephhyyrr-zamfis-frontend

# Nama proyek yang akan tampil di dashboard SonarQube
sonar.projectName=zamfis-frontend

# Versi proyek (opsional, tapi bagus untuk dilacak)
sonar.projectVersion=1.0

# Path ke source code utama yang akan dianalisis
sonar.sources=.

# Pengecualian file dan folder yang tidak perlu dianalisis (PENTING!)
# Jika tidak dikecualikan, laporan analisis akan membengkak dan diblokir Cloudflare (Error 413)
sonar.exclusions=node_modules/**, dist/**, build/**, .nuxt/**, .output/**, public/**, **/*.xlsx, coverage/**, **/*.py

# Encoding source code
sonar.sourceEncoding=UTF-8

# Membatasi memori (RAM) yang digunakan oleh proses analisis Node.js
# menjadi sekitar 1GB (1024 MB).
sonar.javascript.node.maxspace=1024

# Beritahu SonarQube untuk membandingkan semua perubahan
# dengan kondisi terakhir di branch 'main'.
sonar.newCode.referenceBranch=main